# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studemt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='first_pref',
        ),
        migrations.RemoveField(
            model_name='hello',
            name='student',
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
