# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Studemt', '0004_auto_20160920_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='fourth_pref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='Studemt.Subject'),
        ),
        migrations.AddField(
            model_name='hello',
            name='third_pref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='Studemt.Subject'),
        ),
    ]
