# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Studemt', '0005_auto_20160920_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='first_pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='Studemt.Subject'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='fourth_pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='Studemt.Subject'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='second_pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='Studemt.Subject'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='third_pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='Studemt.Subject'),
        ),
    ]
