# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Studemt', '0006_auto_20160920_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='first_pref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='Studemt.Subject'),
        ),
    ]
