# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studemt', '0007_auto_20160920_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
    ]
