# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studemt', '0008_auto_20160921_0538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zero',
        ),
        migrations.AlterModelTable(
            name='hello',
            table='StudentPreference',
        ),
    ]
