# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studemt', '0010_auto_20160921_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hello',
            options={'verbose_name_plural': 'Student Preference'},
        ),
    ]
